#!/usr/bin/env ansible-playbook

- name: Deploy
  hosts: fridge
  vars:
    username: fridge
    password: $1$/O16HWSN$vYfAEF0j2LpEfx5WFtj/4/
    remote_root: /opt/fridge
    remote_reader: "{{ remote_root }}/reader"
    remote_server: "{{ remote_root }}/server"
    remote_web: "{{ remote_root }}/web"
    remote_log: /var/log/fridge
    remote_service: /usr/lib/systemd/system
    local_src: "{{ playbook_dir }}/src"
    local_service: "{{ playbook_dir }}/service"

  roles:
    - init
    - reader
    - server
