CREATE TABLE IF NOT EXISTS fridge_data (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    channel INT NOT NULL,
    temp_c FLOAT NOT NULL,
    temp_f FLOAT NOT NULL
);
