- name: Create remote directory
  become: true
  ansible.builtin.file:
    path: "{{ app_dest }}"
    state: directory
    mode: "0755"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Copy code
  become: true
  ansible.builtin.copy:
    src: "{{ app_src }}/{{ item }}"
    dest: "{{ app_dest }}/{{ item }}"
    mode: "0644"
    owner: "{{ username }}"
    group: "{{ username }}"
  loop: "{{ app_files }}"

- name: Install Dependencies
  become: true
  become_user: "{{ username }}"
  ansible.builtin.pip:
    state: present
    requirements: requirements.txt
    virtualenv: .venv
    chdir: "{{ app_dest }}"

- name: Copy Service
  become: true
  ansible.builtin.template:
    # src: "{{ local_service }}/{{ app_service }}"
    src: app.service.j2
    dest: "{{ remote_service }}/{{ app_service }}"
    mode: "0644"

- name: Start systemd service
  become: true
  ansible.builtin.systemd:
    name: "{{ app_service }}"
    state: started
    enabled: true
    daemon_reload: true
    scope: system
  tags:
    - start_service
