- name: Create remote directory
  become: true
  ansible.builtin.file:
    path: "{{ remote_server }}"
    state: directory
    mode: "0755"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Copy code
  become: true
  ansible.builtin.copy:
    src: "{{ local_src }}/server/{{ item }}"
    dest: "{{ remote_server }}/{{ item }}"
    mode: "0644"
    owner: "{{ username }}"
    group: "{{ username }}"
  loop:
    - server.py
    - requirements.txt
    - run.sh
    - server.conf

- name: Install Dependencies
  become: true
  become_user: "{{ username }}"
  ansible.builtin.pip:
    state: present
    requirements: requirements.txt
    virtualenv: .venv
    chdir: "{{ remote_reader }}"

- name: Copy Service
  become: true
  ansible.builtin.copy:
    src: "{{ local_service }}/server.service"
    dest: "{{ remote_service }}/server.service"
    mode: "0644"

- name: Start systemd service
  become: true
  ansible.builtin.systemd:
    name: server.service
    state: started
    enabled: true
    daemon_reload: true
    scope: system
  tags:
    - start_service
