- name: Install Apt Dependencies
  become: true
  ansible.builtin.apt:
    update_cache: true
    state: present
    name:
      - python3
      - python3-pip
      - python3-venv
      - nodejs
      - npm
      - yarn
      - acl
      - virtualenv

- name: Create user
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    group: "{{ username }}"
    password: "{{ password }}"
    state: present

- name: Create remote root
  become: true
  ansible.builtin.file:
    path: "{{ remote_root }}"
    state: directory
    mode: "0755"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Create remote log
  become: true
  ansible.builtin.file:
    path: "{{ remote_log }}"
    state: directory
    mode: "0755"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Create remote data
  become: true
  ansible.builtin.file:
    path: "{{ remote_data }}"
    state: directory
    mode: "0755"
    owner: "{{ username }}"
    group: "{{ username }}"
